version: 0.2

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS

  pre_build:
    commands:
      - dotnet restore
      - dotnet test --no-restore
  
  build:
    commands:
      - dotnet build
      - echo building!
  
artifacts:
  files:
    - 'Dockerfile'
    - '**/*'