#We want our SDK image
from mcr.microsoft.com/dotnet/sdk:5.0 as build

#Create our working director
workdir /app

#Copying our projects to our working directory
copy *.sln ./
copy RRBL/*.csproj RRBL/
copy RRDL/*.csproj RRDL/
copy RRTest/*.csproj RRTest/
copy RRModels/*.csproj RRModels/
copy RRWebAPI/*.csproj RRWebAPI/

#Restore our dependencies on each project
run cd RRWebAPI && dotnet restore

#Copy the source code
copy . ./

#Publish the application for deployment
run dotnet publish RRWebAPI -c Release -o publish --no-restore

#After getting all the dependencies restored and created our publish folder
#We don't need SDK as our environment anymore
#To save space we will change our image environment to just the runtime of .Net
from mcr.microsoft.com/dotnet/aspnet:5.0 as runtime

workdir /app
copy --from=build /app/publish ./

#CMD to set that RRWebApi.dll assembly will be our default entrypoint
cmd ["dotnet", "RRWebAPI.dll"]

#Expose to port 80
expose 80