# YML is another markup language that is sentitive to "spaces" so careful where you tab your keywords
# In this case, we are telling the Github server should do to be able to deploy our api
name: Build, Test, and Deploy API

# We specify when should this action should execute depending on what is happening on your remote repository
on:
  # This is stating it will trigger if a push happens on main
  push:
    branches: [ main ]
  # This is stating it will trigger on pull request
  pull_request:
    branches: [ main ]
  
# Jobs are just mutliple things you might want to do in this computer/server
# Right now we only have one job which is to deploy
jobs:

  # This is where we state a bunch of configuration
  build:
    runs-on: windows-latest # We are stating that the github server/computer will run on the Linux OS
    environment:
      name: 'Production'
    defaults:
      run:
        working-directory: 6-DevOps/Poke # This might differ depending on where your project/app is in your remote repo
    
    # Steps are just the sequence of things that this computer/server needs to run to complete a job
    steps:
    
    # We want this computer to have our SDK to even build, test, and deploy
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    # Will setup a JDK for our computer since the SonarQube uses it to run
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    
    # Just gets the necesarry packages for the SonarQube tool
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
        
    # Installing SonarCloud Scanner itself on the computer
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool install dotnet-sonarscanner --version 5.5.3 --tool-path .\.sonar\scanner
          
    # Restore dependencies in our .NET application
    # Essentially, we will get all the external packages we install (ex: System.Data.SqlClient)
    - name: Restore dependencies
      run: dotnet restore
      
    # Doing our unit tests and making sure that all of it passes before even deploying this app
    - name: Test
      run: dotnet test --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    
    # This is the step where you have to configure things
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: pwsh
      run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"220118-Reston-NET_Training-code" /o:"220118-reston-net" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.coverage.exclusions=**/PokeApi/wwwroot/lib/**,**/**PokeDL/*.cs,**/PokeApi/Controllers/*.cs /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.vstest.reportsPath="**/TestResults/*.trx"
          dotnet build ./PokeApi -c Release
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      
    # We are creating our publish folder for us to use
    - name: Create Publish folder
      run: dotnet publish -c Release -o publish
      
    # Deploying our app to our Azure Webapp
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: PokeDemo
        slot-name: 'Production'
        publish-profile: $${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
        package: 6-DevOps/Poke/publish
