using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

/*
    Auto generated by utilizing dotnet-aspnet-codegenerator tool
     -Installed via dotnet tool install -g dotnet-aspnet-codegenerator
     -Followed by dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design

    After everything is installed run this command
    dotnet aspnet-codegenerator controller -name Test -api -outDir Controllers -actions

    "dotnet aspnet-codegenerator controller" - means we are creating a controller

    "-name {NameOfController}" - Specifies what the name will be
    
    "-api" - Tells that this controller is specifically for api

    "-outDir" - Tells where we want to place that file (relative to where the terminal is)

    "-actions" - autogenerates default read/write actions inside the controller
*/

namespace PokeApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PokemonController : ControllerBase
    {
        // GET: api/Pokemon
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/Pokemon/5
        [HttpGet("{id}", Name = "Get")]
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/Pokemon
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT: api/Pokemon/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE: api/Pokemon/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}
