using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PokeBL;
using PokeModel;

/*
    Auto generated by utilizing dotnet-aspnet-codegenerator tool
     -Installed via dotnet tool install -g dotnet-aspnet-codegenerator
     -Followed by dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design

    After everything is installed run this command
    dotnet aspnet-codegenerator controller -name Test -api -outDir Controllers -actions

    "dotnet aspnet-codegenerator controller" - means we are creating a controller

    "-name {NameOfController}" - Specifies what the name will be
    
    "-api" - Tells that this controller is specifically for api

    "-outDir" - Tells where we want to place that file (relative to where the terminal is)

    "-actions" - autogenerates default read/write actions inside the controller
*/

namespace PokeApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PokemonController : ControllerBase
    {
        private IPokemonBL _pokeBL;
        public PokemonController(IPokemonBL p_pokeBL)
        {
            _pokeBL = p_pokeBL;
        }


        // GET: api/Pokemon
        [HttpGet("GetAllPokemon")]
        public IActionResult GetAllPokemon()
        {
            try
            {
                List<Pokemon> listOfPokemon = _pokeBL.GetAllPokemon();

                return Ok(listOfPokemon); //Returns a 200 status code
            }
            catch (SqlException)
            {
                //The API is responsible for sending the right status codes
                //It is entirely possible that a developer sends a 200 status code like everything is fine but in reality it didn't
                //the request properly
                return NotFound(); //Returns a 404 not found status code means it was unable to locate the resource
            }
        }

        // GET: api/Pokemon/5
        [HttpGet("{id}", Name = "GetPokemonAbilities")]
        public string GetPokemonAbilities(int p_pokeId)
        {
            return "value";
        }

        // POST: api/Pokemon
        [HttpPost]
        public void Post([FromBody] string value)
        {

        }

        // PUT: api/Pokemon/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE: api/Pokemon/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}
