version: 0.2

phases:
  install:
    commands:
      - yum update httpd
      - rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
      - sudo yum install dotnet-sdk-6.0

  pre_build:
    commands:
      - cd 6-DevOps/Day-3/Poke
      - dotnet restore
      - dotnet test --no-restore
  
  build:
    commands:
      - dotnet build
      - echo building!
  
artifacts:
  files:
    - .\6-DevOps\Day-3\Poke\dockerfile