version: 0.2

phases:
  pre_build:
    commands:
      - cd 6-DevOps/Day-3/Poke
      - dotnet restore
      - dotnet test --no-restore
  
  build:
    commands:
      - dotnet build
      - echo building!
  
artifacts:
  files:
    - .\6-DevOps\Day-3\Poke\dockerfile