version: 0.2

phases:
  install:
    commands:
      - wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - rm packages-microsoft-prod.deb
      - sudo apt-get update
      - sudo apt-get install apt-transport-https
      - sudo apt-get update
      - sudo apt-get install dotnet-sdk-6.0

  pre_build:
    commands:
      - cd 6-DevOps/Day-3/Poke
      - dotnet restore
      - dotnet test --no-restore
  
  build:
    commands:
      - dotnet build
      - echo building!
  
artifacts:
  files:
    - .\6-DevOps\Day-3\Poke\dockerfile