version: 0.2

phases:
  build:
    commands:
      - cd .\6-DevOps\Day-3\Poke\
      - dotnet build
      - dotnet publish -c Release -r linux-x64 --self-contained true
  
  artifacts:
    files:
      - 'DockerFile'
      - .\6-DevOps\Day-3\Poke\