#Getting .NET 6 runtime to just run our application
from mcr.microsoft.com/dotnet/aspnet:latest as runtime

# Setting our working directory
workdir /app

# Copying the publish folder generated by our CodeBuild
copy /publish ./

#Entrypoint to set that PokeApi.dll assembly will be our default entrypoint
entrypoint ["dotnet", "PokeApi.dll"]

#Expose to port 5000
expose 5000

#Changes the port from the runtime image to listen to 5000 (since by default it uses port 80)
env ASPNETCORE_URLS=http://+:5000